### ISSUE TITLE
Выложить готовые релизы

### ISSUE THREAD

**Issue by artbear** [e8tools/v8unpack#10]
Предлагаю где-нибудь выложить готовые релизы, чтобы пользователи могли использовать продукт.
Либо в Вики, либо как артефакт на своем build-сервере (если есть)

**Comment by dmpas** [comment]
Понял, уделю время серверу сборок.
Последний мастер с 32-битной сборкой пока что можно скачать тут: http://share.dmpas.ru/ge8/abcdef/v8unpack.zip

**Comment by artbear** [comment]
ОФФ. А у тебя уже есть/юзается какой-нибудь билд-сервер для других проектов?

**Comment by dmpas** [comment]
[jenkins](https://build.batanov.me/)

**Comment by artbear** [comment]
А как увидеть сборку для v8unpack ? сейчас там пусто

**Comment by dmpas** [comment]
Ну так сейчас там её и нет. Во всяком случае под винду. Под линукс была пробная сборка.

**Comment by artbear** [comment]
Я к тому, что анонимусу видны 4 сборки, среди них ничего похожего на v8unpack не вижу.

**Comment by dmpas** [comment]
Раньше просто не было нужды ковыряться с правами.
Проба пера для win64: https://build.batanov.me/view/e8-script/job/v8unpack-win/

**Comment by dmpas** [comment]
Настроил. Должно работать по этим ссылкам:

Сборка win32:
https://build.batanov.me/view/e8-script/job/v8unpack-win/label=mingw32/lastSuccessfulBuild/artifact/bin/Release/*zip*/v8unpack.zip

Сборка win64:
https://build.batanov.me/view/e8-script/job/v8unpack-win/label=mingw64/lastSuccessfulBuild/artifact/bin/Release/*zip*/v8unpack.zip

**Comment by artbear** [comment]
Закинь эти ссылки в readme.md, пожалуйста.

> Артефакты/релизы можно скачать с [build-server проекта](https://build.batanov.me/job/v8unpack-win/)
> 
> [Прямая ссылка на последнюю успешную сборку win32](https://build.batanov.me/view/e8-script/job/v8unpack-win/label=mingw32/lastSuccessfulBuild/artifact/bin/Release/*zip*/v8unpack.zip)
> 
> [Прямая ссылка на последнюю успешную сборку win64](https://build.batanov.me/view/e8-script/job/v8unpack-win/label=mingw64/lastSuccessfulBuild/artifact/bin/Release/*zip*/v8unpack.zip)

**Comment by dmpas** [comment]
Может, лучше в вики?

**Comment by dmpas** [comment]
Положил ссылки в Вики.
