### ISSUE TITLE
В архиве с 32разрядным архивом для Windows нет файла v8unpack.exe

### ISSUE THREAD

**Issue by artbear** [e8tools/v8unpack#16]
Смотрю на билд-сервере
https://build.batanov.me/job/v8unpack-win/label=mingw32/
В архиве с 32разрядным архивом для Windows нет файла v8unpack.exe

```
Артефакты последних удачных сборок
    libgcc_s_dw2-1.dll  109.51 KB    view
    libstdc++-6.dll 977.51 KB    view
    pthreadGC2.dll
```

Где взять последнюю версию?

**Comment by dmpas** [comment]
Упс. Сборочник-то, оказывается, не пашет уже месяца два... Чиню.

**Comment by dmpas** [comment]
@artbear всё, засобиралось.

**Comment by artbear** [comment]
Да, все в порядке.
