### ISSUE TITLE
При сборке на Убунте 15.10 выдает длинный трейс ошибок

### ISSUE THREAD

**Issue by vgulaev** [e8tools/v8unpack#17]
g++ -D__LINUX -Wall -O2  -c src/V8File.cpp -o obj/Release/src/V8File.o
src/V8File.cpp: In member function ‘int CV8File::UnpackToDirectoryNoLoad(const string&, std::basic_ifstream<char>&, ULONG, bool, bool)’:
src/V8File.cpp:476:13: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "UnpackToFolder. Error in creating directory!" << std::endl;
             ^
src/V8File.cpp: In member function ‘int CV8File::UnpackToFolder(const string&, const string&, char_, bool)’:
src/V8File.cpp:629:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Input file not found!" << std::endl;
         ^
src/V8File.cpp:639:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Not enough memory!" << std::endl;
         ^
src/V8File.cpp:645:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Error in reading file!" << std::endl;
         ^
src/V8File.cpp:656:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. This is not V8 file!" << std::endl;
         ^
src/V8File.cpp:660:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Error in load file in memory!" << std::endl;
         ^
src/V8File.cpp:666:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Error in creating directory!" << std::endl;
         ^
src/V8File.cpp:675:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Error in creating file!" << std::endl;
         ^
src/V8File.cpp:686:9: error: ‘cout’ is not a member of ‘std’
         std::cout << "Progress (50 points): " << std::flush;
         ^
src/V8File.cpp:695:17: error: ‘cout’ is not a member of ‘std’
                 std::cout << "|" << std::flush;
                 ^
src/V8File.cpp:697:17: error: ‘cout’ is not a member of ‘std’
                 std::cout << "." << std::flush;
                 ^
src/V8File.cpp:713:13: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "UnpackToFolder. Error in creating file!" << std::endl;
             ^
src/V8File.cpp:726:13: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "UnpackToFolder. Error in creating file!" << std::endl;
             ^
src/V8File.cpp:737:9: error: ‘cout’ is not a member of ‘std’
         std::cout << std::endl;
         ^
src/V8File.cpp: In member function ‘int CV8File::ReadBlockData(char_, CV8File::stBlockHeader_, char_&, UINT_)’:
src/V8File.cpp:774:13: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "ReadBlockData. BlockData == NULL." << std::endl;
             ^
src/V8File.cpp: In member function ‘int CV8File::ReadBlockData(std::basic_ifstream<char>&, CV8File::stBlockHeader_, char_&, UINT_)’:
src/V8File.cpp:814:13: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "ReadBlockData. BlockData == NULL." << std::endl;
             ^
src/V8File.cpp: In member function ‘int CV8File::Parse(const string&, const string&, int)’:
src/V8File.cpp:1076:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Input file not found!" << std::endl;
         ^
src/V8File.cpp:1086:5: error: ‘cout’ is not a member of ‘std’
     std::cout << "LoadFile: ok" << std::endl;
     ^
src/V8File.cpp: In member function ‘int CV8File::SaveFileToFolder(const string&) const’:
src/V8File.cpp:1099:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "UnpackToFolder. Error in creating directory!" << std::endl;
         ^
src/V8File.cpp:1112:9: error: ‘cout’ is not a member of ‘std’
         std::cout << "Progress (50 points): " << std::flush;
         ^
src/V8File.cpp:1123:17: error: ‘cout’ is not a member of ‘std’
                 std::cout << "|" << std::flush;
                 ^
src/V8File.cpp:1125:17: error: ‘cout’ is not a member of ‘std’
                 std::cout << ".";
                 ^
src/V8File.cpp:1137:17: error: ‘cerr’ is not a member of ‘std’
                 std::cerr << "SaveFile. Error in creating file!" << std::endl;
                 ^
src/V8File.cpp:1149:9: error: ‘cout’ is not a member of ‘std’
         std::cout << std::endl << std::flush;
         ^
src/V8File.cpp: In member function ‘int CV8File::Build(const string&, const string&, int)’:
src/V8File.cpp:1245:5: error: ‘cout’ is not a member of ‘std’
     std::cout << "LoadFileFromFolder: ok" << std::endl;
     ^
src/V8File.cpp:1249:5: error: ‘cout’ is not a member of ‘std’
     std::cout << "Pack: ok" << std::endl;
     ^
src/V8File.cpp: In member function ‘int CV8File::SaveFile(const string&)’:
src/V8File.cpp:1260:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "SaveFile. Error in creating file!" << std::endl;
         ^
src/V8File.cpp: In member function ‘int CV8File::BuildCfFile(const string&, const string&)’:
src/V8File.cpp:1320:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "Argument error - Set of `in_dirname' argument" << std::endl;
         ^
src/V8File.cpp:1325:9: error: ‘cerr’ is not a member of ‘std’
         std::cerr << "Argument error - Set of`out_filename' argument" << std::endl;
         ^
src/V8File.cpp:1335:13: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "Build error. Directory `" << in_dirname << "` is empty.";
             ^
src/V8File.cpp:1368:9: error: ‘cout’ is not a member of ‘std’
         std::cout << "SaveFile. Error in creating file!" << std::endl;
         ^
src/V8File.cpp:1379:9: error: ‘cout’ is not a member of ‘std’
         std::cout << "Progress (50 points): " << std::flush;
         ^
src/V8File.cpp:1402:21: error: ‘cout’ is not a member of ‘std’
                     std::cout << "|" << std::flush;
                     ^
src/V8File.cpp:1404:21: error: ‘cout’ is not a member of ‘std’
                     std::cout << ".";
                     ^
src/V8File.cpp:1474:5: error: ‘cout’ is not a member of ‘std’
     std::cout << std::endl << "Build OK!";
     ^
src/V8File.cpp: In member function ‘int CV8File::Pack()’:
src/V8File.cpp:1536:9: error: ‘cout’ is not a member of ‘std’
         std::cout << "Progress (50 points): " << std::flush;
         ^
src/V8File.cpp:1548:17: error: ‘cout’ is not a member of ‘std’
                 std::cout << "|" << std::flush;
                 ^
src/V8File.cpp:1550:17: error: ‘cout’ is not a member of ‘std’
                 std::cout << ".";
                 ^
src/V8File.cpp:1581:9: error: ‘cout’ is not a member of ‘std’
         std::cout << std::endl;
         ^
Makefile:59: recipe for target 'obj/Release/src/V8File.o' failed
make: **\* [obj/Release/src/V8File.o] Error 1

**Comment by dmpas** [comment]
@vgulaev вечером посмотрю. Пока навскидку: установлен пакет libstdc++-dev ?

**Comment by vgulaev** [comment]
@dmpas 
Какую версию поставить?
  libstdc++-4.8-dev 4.8.5-1ubuntu1
  libc++-dev 3.5-2
  libstdc++6-4.7-dev 4.7.4-3ubuntu3
  libstdc++-5-dev 5.2.1-22ubuntu2
  libstdc++-4.9-dev 4.9.3-5ubuntu1

Поставил   libstdc++6-4.7-dev непомогло

**Comment by vgulaev** [comment]
собралось

**Comment by pumbaEO** [comment]
Чего в результате не хватало?

2016-01-28 17:20 GMT+03:00 Valentin notifications@github.com:

> собралось
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dmpas/v8unpack/issues/17#issuecomment-176204570.

## 

З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by vgulaev** [comment]
@pumbaEO 
Видимо магии, потому что поставил много чего и чего не хватало не понятно.

**Comment by dmpas** [comment]
Странно. Вот такой докер у меня собирает без ошибок:

```
  1 FROM ubuntu:wily
  2 
  3 RUN apt-get update
  4 RUN apt-get install -y git g++ make
  5 RUN apt-get install -y libboost-filesystem-dev libboost-system-dev zlib1g-dev
  6 
  7 RUN mkdir -p /root/workspace/v8unpack
  8 RUN git clone https://github.com/dmpas/v8unpack.git /root/workspace/v8unpack
  9 
 10 CMD ["make", "-C", "/root/workspace/v8unpack"]
```

то есть, при установке `libboost-filesystem-dev libboost-system-dev zlib1g-dev` с зависимостями подтянулось всё необходимое для сборки.

**Comment by pumbaEO** [comment]
Я скопировал ppa для wily и мне тоже выдало ошибку сборки

https://launchpad.net/~pumbaeo/+archive/ubuntu/e8test/+build/8908347

28 января 2016 г., 18:24 пользователь Sergey Batanov <
notifications@github.com> написал:

> Странно. Вот такой докер у меня собирает без ошибок:
> 
>   1 FROM ubuntu:wily
>   2
>   3 RUN apt-get update
>   4 RUN apt-get install -y git g++ make
>   5 RUN apt-get install -y libboost-filesystem-dev libboost-system-dev zlib1g-dev
>   6
>   7 RUN mkdir -p /root/workspace/v8unpack
>   8 RUN git clone https://github.com/dmpas/v8unpack.git /root/workspace/v8unpack
>   9
>  10 CMD ["make", "-C", "/root/workspace/v8unpack"]
> 
> то есть, при установке libboost-filesystem-dev libboost-system-dev
> zlib1g-dev с зависимостями подтянулось всё необходимое для сборки.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dmpas/v8unpack/issues/17#issuecomment-176234750.

## 

З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by dmpas** [comment]
@pumbaEO забавно, в [прошлый раз](https://launchpadlibrarian.net/210186665/buildlog_ubuntu-trusty-i386.v8unpack_3.0.36-1_BUILDING.txt.gz) он libsdc++-dev поставил сам. Очевидно, надо явно его в control прописать для надёжности.

**Comment by pumbaEO** [comment]
@dmpas тогда может и добавишь сразу другие версии в build план?

**Comment by dmpas** [comment]
@pumbaEO посмотрю на досуге. но делать пакеты для PPA - то ещё развлечение, потому это не скоро будет.

**Comment by dmpas** [comment]
@pumbaEO я так не играю! https://launchpad.net/~dmpas/+archive/ubuntu/e8/+build/10752422
ланчпад ровно те же исходники собрал под сеню без единого нарекания.
