### ISSUE TITLE
Добавить сборку без упаковки данных (для форм)

### ISSUE THREAD

**Issue by pumbaEO** [e8tools/v8unpack#20]
При сборке форм указывают, что нет необходимости сжимать дополнительно готовый контейнер
https://github.com/silverbulleters/vanessa-runner/issues/27

При этом https://github.com/dmpas/v8unpack/blob/master/src/V8File.cpp#L1540 явно указывается сжатие.

**Comment by Infactum** [comment]
Предлагаю просто опцию --nested добавить, чтобы было ясно когда требуется собрать основной контейнер, а когда вложенный.

**Comment by dmpas** [comment]
а `-pack` вместо `-build` не срабатывает?

**Comment by Infactum** [comment]
С `-pack` даже близко результат не тот.
...
Хотя если распаковывать не через `-parse` а через `-unpack`, то будет норм. Правда мусорных файлов больше.

**Comment by dmpas** [comment]
Подпилим - не вопрос.

**Comment by dmpas** [comment]
@pumbaEO @Infactum https://ci.appveyor.com/api/buildjobs/qwwtp9drob4okm0j/artifacts/Release%2Fv8unpack.exe

Сборочка. Мне сейчас толком потестить не на чем.

**Comment by Infactum** [comment]
@dmpas работает
