### ISSUE TITLE
Неполная установка через ppa в ubuntu

### ISSUE THREAD

**Issue by Infactum** [e8tools/v8unpack#21]
Ставлю через PPA на "голую" ситсему.
После установки не хватает для запуска пакета lib boost filesystem.
В идеале хотелось бы статик линковку. Либо исправить ppa.

**Comment by pumbaEO** [comment]
Т.е. зависимости не прописаны?

**Comment by dmpas** [comment]
ага. посмотрел: Build-Depends есть, а Depends пустой. не судите строго - это был первый пакет в моей жизни :)

**Comment by Infactum** [comment]
А можно все-таки статик линковку сделать? Потому что весь пакет lib-boost-filesystem не слабо так весит на фоне v8unpack.

**Comment by dmpas** [comment]
Можно, почему бы и нет.

**Comment by dmpas** [comment]
@Infactum статика против шареда прибавку в мегабайт даёт. Многовато, нет?

**Comment by dmpas** [comment]
@Infactum обновил пакеты в PPA.
