### ISSUE TITLE
Проблема с обратной сборкой конфы после разборки

### ISSUE THREAD

**Issue by 1C-Romania** [e8tools/v8unpack#27]
Имеем: 
некую Конфигурацию - старенькую, на обычных формах, но вполне функциональную и исправную ("выгрузка в файлы" и обратная "загрузка из файлов" средствами Платформы проходят успешно)

Что делаем:
1) разбираем конфу командой
v8unpack.exe -u cfname.cf dirname

2) собираем конфу командой
v8unpack.exe -pack dirname cfname01.cf
при сравнении/объединении полученного CFшника с изначальной конфой - не выдает различий (!), но попытка "заглянуть" в любую Форму выдает "Ошибку потока"

3) собираем конфу командой
v8unpack.exe -build dirname cfname02.cf
или командой
v8unpack.exe -build -nopack dirname cfname03.cf
при попытке загрузить в новую базу или при сравнении/объединении полученных CFшников с изначальной конфой - выдает "Configuration Structure is incompatible with current program version"

изначальный CFшник приложить?

**Comment by artbear** [comment]
Версия v8unpack ?

**Comment by dmpas** [comment]
> некую Конфигурацию - старенькую

и версия совместимости конфы?

**Comment by 1C-Romania** [comment]
v8unpack -v  =  3.0.38
Compatibility mode = 8.3.6

**Comment by 1C-Romania** [comment]
Вопрос закрывается - после полного снятия с конфигурации "Совместимости" - все собралось!

**Comment by dmpas** [comment]
@1C-Romania нененене, не снимается! можно эту чудо конфу получить? не должно же быть такого: unpack/pack вообще по-тупому и без логики отрабатывают, там просто нечему сбоить.

**Comment by 1C-Romania** [comment]
@dmpas , извините - только сейчас заметил ваш вопрос...   8-(
да, конечно, все можно - как связаться "в личку"?

**Comment by dmpas** [comment]
@1C-Romania 
sergey.batanov@dmpas.ru
