### ISSUE TITLE
Определиь лицензию на код

### ISSUE THREAD

**Issue by pumbaEO** [e8tools/v8unpack#28]
Необходимо определить лицензию на код. 
@demidych можешь сделать pull с лицензией ?

**Comment by demidych** [comment]
Честно говоря в этом не разбираюсь.
Я не против любой лицензии, но чтобы ссылка на меня оставалась в коде и в инфо о программе (как сейчас и сделано).

**Comment by dmpas** [comment]
MIT, Apache, MPL, GPL - любая обязывает сохранять авторство. Осталось определиться с требованием раскрывать исходники доработок. @demidych @pumbaEO

**Comment by dmpas** [comment]
Раз все молчат, будет мозилла, как в односкрипте. @demidych @pumbaEO
