### ISSUE TITLE
При запуске 3.0.38 выдается ошибка отсутствия необходимых dll

### ISSUE THREAD

**Issue by artbear** [e8tools/v8unpack#29]
+ MSVCR120.dll
+ MSVCP120.dll

Windows 10

Как побороть ошибку?

**Comment by artbear** [comment]
Связано с https://github.com/xDrivenDevelopment/precommit1c/issues/105

**Comment by artbear** [comment]
В доке информации о решении не увидел.

**Comment by dmpas** [comment]
какой-то из редистов надо поставить.

https://www.microsoft.com/ru-ru/download/details.aspx?id=53840


Видимо, под винду надо тоже в статику всё линковать :(

**Comment by artbear** [comment]
Статику сделаешь?

**Comment by dmpas** [comment]
Сделаю, но пока редист поставь.

**Comment by dmpas** [comment]
Весь мозг свернул, как это на аппвеёре просто сделать. @artbear оно тебе сильно надо??..

**Comment by artbear** [comment]
Неужели редист на аппвейоре не ставится в сайлент режиме??

Так-то обход есть, но инструмент у нас везде юзается.
сейчас мы его просто копируем/клонируем, а придется заставлять еще доп.приложения ставить.
и это всем пользователям :(

**Comment by dmpas** [comment]
редист на аппвеёре не нужен, там же целиковая студия стоит. редист нужен на конечной машине. а чтобы он там был не нужен, нужно статику линковать, а для этого надо zlib собирать со статикой, а он, гадина, не даёт наружу настроек - надо ковыряться.
то есть, если сильно жизнь портит, я займусь, если просто мелкое неудобство, то я бы 39-ю выпустил, а потом на досуге продолжил этой задачкой заниматься.

**Comment by artbear** [comment]
Конечно, выпускай 39, пока супербольших жалоб по сабжу не было

**Comment by dmpas** [comment]
@artbear 
https://ci.appveyor.com/api/buildjobs/7unioqr8j2daipg7/artifacts/Release%2Fv8unpack.exe

попробуй

**Comment by artbear** [comment]
Отлично. работает.
Будет официальной версией?

**Comment by dmpas** [comment]
@artbear да.
