### ISSUE TITLE
Запилить сборку deb-пакета в Makefile

### ISSUE THREAD

**Issue by dmpas** [e8tools/v8unpack#3]

**Comment by pumbaEO** [comment]
Не проще autotools? Тогда не только deb но и rpm можно будет собирать с минимальніьми телодвижениями?

**Comment by dmpas** [comment]
С этим зверем я ещё не знаком, а вот как собрать deb хотя бы в теории знаю.

**Comment by dmpas** [comment]
Запилена сборка deb-пакетов через launchpad.
