### ISSUE TITLE
Обработка по списку

### ISSUE THREAD

**Issue by demidych** [e8tools/v8unpack#30]
Предлагаю добавить возможность передавать данные для обработки списком в файле.
Например, это полезно при распаковке (parse) всех неуправляемых форм для помещения в git.

Формат файла-списка - в каждой строке входной файл/каталог и выходной файл/каталог с разделителем (например, точка с запятой).

Параметр можно назвать -L[IST] и тогда вызов для распаковки будет такой:

```
v8unpack -parse -list list.txt
```

Содержимое list.txt
```
a\form.bin;a\form
b\form.bin;b\form
c with spaces\form.bin;c with spaces\form
```

**Comment by dmpas** [comment]
неужели проще составить такой список, чем сразу вызвать v8unpack каждый раз? Или такой список уже откуда-то готовый получается и хочется просто его скормить распаковщику?

**Comment by demidych** [comment]
Мне кажется один вызов будет быстрее чем "вызывать v8unpack каждый раз".
Особенно, если стоит антивирус, который похоже проверяет v8unpack.exe при каждом запуске.

И еще это спасает от открытия кучи окон, которые блокируют работу, если не скрывать запуск приложения, например для отладки.

Также список формирует 8.3.10 (с ключами -update -getChanges changes.txt). Правда он не пути содержит, а полные имена объектов. Например, при изменении "обычной" формы элемента в Справочник5 формируется файл:
```
Modified:Catalog.Справочник5.Form.ФормаЭлемента
Modified:Catalog.Справочник5.Form.ФормаЭлемента.Form
```

**Comment by dmpas** [comment]
Эти ваши винды с этими вашими антивирусами... Посыл понял, покумекаю.

**Comment by artbear** [comment]
Ага, мне также нравится данная идея.
Только не забыть выдавать в лог сообщения для каждого файла.

**Comment by dmpas** [comment]
@demidych @artbear 
https://ci.appveyor.com/api/buildjobs/7unioqr8j2daipg7/artifacts/Release%2Fv8unpack.exe

пробуем, жалуемся

**Comment by artbear** [comment]
@dmpas Формат списка опиши, плиз.
Учтены  оба замечания @demidych ?

**Comment by dmpas** [comment]
@artbear 
> Формат списка опиши

в доку или куда?

> Учтены оба замечания

туплю, ткни носом в "оба" замечания?

**Comment by demidych** [comment]
Парочка замечаний:

1. С кодировкой файла со списком есть "особенности". Работает только если файл в кодировке 1251, а не 866, что вроде как неправильно.
2. При обработке выводит бесполезное "LoadFile: ok" для каждого файла. Надо либо убрать, либо добавить какой файл "ok".

**Comment by dmpas** [comment]
Предлагаю смириться с 1251. Уж очень хочется поскорее избавиться от этого мерцания...

**Comment by demidych** [comment]
А я уже давно пользуюсь =)

**Comment by artbear** [comment]
@dmpas Через хелп программы через ком.строке непонятен формат параметра list.
Добавь, плиз, одну-две строки в хелп для описания этого параметра. чтобы народу было проще пользоваться.
