### ISSUE TITLE
Неправильная распаковка/запаковка cf,  с большим файлом конфигурации поставщика внутри

### ISSUE THREAD

**Issue by bolsun** [e8tools/v8unpack#38]
Имеется большая конфигурация на поддержке. Размер cf ~700Mb. Файл поставщика внутри ~400Mb.

После выполнения parse и build размер cf становится  всего 270Mb и имеет неверный формат. При попытке повторной распаковки выдает UnpackToFolder. `1cv8.cf` is not V8 file!

**Comment by dmpas** [comment]
УПП? ЕРП? на чём попробовать?

**Comment by bolsun** [comment]
Возникает в конфигурации "Бухгалтерия государственного учреждения" 2.0.48.64. Платформа 8.3.8.1652. Конфигурация доработана, но на поддержке. При снятой поддержке, запаковывается правильно.

**Comment by dmpas** [comment]
Спасибо! В воскресенье посмотрю. Раньше до компа не доберусь.

**Comment by dmpas** [comment]
@bolsun скачал БГУ 2.0.48.64, включил возможность изменения - разбирается-собирается без косяков. Можно конфу получить посмотреть?
