### ISSUE TITLE
v8unpack не работает с 8.3.16 Распаковывает без модулей, только файлы root и version

### ISSUE THREAD

**Issue by bolsun** [e8tools/v8unpack#53]
Во вложении тестовая конфигурация с общим модулем и модулем формы документа.
При распаковке их нет.
[8316_Тестовая.zip](https://github.com/e8tools/v8unpack/files/3626281/8316_.zip)

**Comment by fishca** [comment]
![19_09_cf](https://user-images.githubusercontent.com/1484649/65270491-f1e27800-db23-11e9-91c5-69d8f2bab231.png)
Похоже структура поменялась.

**Comment by dmpas** [comment]
судя по картинке, инт32 заменяют на инт64, что не может не радовать.

**Comment by fishca** [comment]
1. Нововведения появились в файле с адреса 135A
2. В файле теперь два раза присутствуют секции root, version, versions
![24 09_1](https://user-images.githubusercontent.com/1484649/65516711-2e2e2380-deea-11e9-92aa-ce05ccf1d0e5.png)
![24_09](https://user-images.githubusercontent.com/1484649/65516712-2ec6ba00-deea-11e9-9cf6-69444ae5ddf3.png)

Судя по скриншотам содержимое данных секций разное.

**Comment by dmpas** [comment]
видимо, старое оставлено для совместимости с младшими версиями, чтобы они выдали внятное сообщение об ошибке. Спасибо за исследование.

**Comment by dmpas** [comment]
@bolsun https://ci.appveyor.com/api/buildjobs/35h2yfu11y86kxls/artifacts/Release%2Fv8unpack.exe
можешь погонять свежую сборку?

**Comment by bolsun** [comment]
> @bolsun https://ci.appveyor.com/api/buildjobs/35h2yfu11y86kxls/artifacts/Release%2Fv8unpack.exe
> можешь погонять свежую сборку?

@dmpas Да, конечно. Нужно также с флагом -P16 или добавилось автоматическое определение формата?

**Comment by dmpas** [comment]
@bolsun Автоматическое теперь.

**Comment by bolsun** [comment]
@dmpas Супер, потестируем.  Спасибо!

**Comment by dmpas** [comment]
https://ci.appveyor.com/api/buildjobs/88i1hs4287ac9rk6/artifacts/Release%2Fv8unpack.exe

@bolsun  обновили сборку

**Comment by bolsun** [comment]
@dmpas проверил для начала на тестовой, все ОК. 
Единственное меня смущает, что размер оригинального файла 88КБ, а распакованного и запакованного заново 18КБ. 
Хотя загружается правильно. Это норма?

**Comment by dmpas** [comment]
@bolsun ну, да. Размер может отличаться, это известная особенность.

Суть в том, что конфигуратор пишет файл конфы с учётом того, что её пилят постоянно - есть пустые страницы внутри файла, пусстое место внутри страниц.

Наша упаковка работает просто и топорно: взять да упаковать без лишних пустот.

**Comment by fishca** [comment]
> Наша упаковка работает просто и топорно: взять да упаковать без лишних пустот.


Не совсем так. Наша упаковка собирает в соответствии с форматом до 8.3.16. Адресация внутренних структур остается 32-битной, а должна быть в формате 64 бита, да еще и не учитывается волшебное смещение.

**Comment by bolsun** [comment]
Парочка вопросов.
1. Раньше программа запускалась на любых машинах, теперь часто возникают ошибки не найдена vcruntime140d.dll, msvcp140d.dll, MSVCP1400.dll и т.д. На разных машинах, по разному. Я понимаю, что нужно VC++ Runtime установить, но не всегда помогает. Решается копированием нужных библиотек в папку с программой, в зависимости от системы. Можно, что-то сделать с этим? Это на предыдущей версии с флагом -P16
2. Новую не удалось пока проверить на этих машинах, т.к. стал ругаться защитник Windows и блокировать запуск, раньше такого также не было.

**Comment by dmpas** [comment]
1. версия с P16 была, как я понимаю, собрана в Студии в отладочном режиме. Потому ей нужны не рантайм библиотеки, а отладочные - то есть из поставки Студии. Потому лучше брать 2

2. Защитник вечно на всё ругается. Не надо запускать программу из каталога скачиваний. Но тем не менее в итоге всё равно придётся пользоваться этими версиями - они специально собираются, чтобы работать без лишних зависимостей. Вся сборка прозрачна для конечного пользователя.

**Comment by bolsun** [comment]
1. Понял спасибо, теперь понятна проблема :)
2. Да я то понимаю это, а пользователи пугаются :) Подписал своим ключом, защитник вроде перестал ругаться. Потестируем.

**Comment by dmpas** [comment]
@bolsun если существует такая проблема, мы тоже можем озаботиться ключом

**Comment by bolsun** [comment]
@dmpas да может и нет проблемы. Просто когда тестировали разные версии из-за отсутствия отладочных библиотек, пользователи скачивали файл по ссылке с яндекс диска и запускали в проводнике, поэтому может ругался защитник.  Если запускать из командной строки или bat файла, то вроде не ругается.

**Comment by LazarenkoA** [comment]
> https://ci.appveyor.com/api/buildjobs/88i1hs4287ac9rk6/artifacts/Release%2Fv8unpack.exe
> 
> @bolsun обновили сборку

с ключом -P работает, а если -U то файлов очень мало получается

**Comment by dmpas** [comment]
@LazarenkoA 
мы тут немного пофиксили:
https://ci.appveyor.com/project/dmpas/v8unpack-wvig5/builds/41585890/artifacts
