### ISSUE TITLE
Упаковка в формат 8.3.16

### ISSUE THREAD

**Issue by dmpas** [e8tools/v8unpack#61]

**Comment by dmpas** [comment]
В файле формата 64х получается два слоя:
* старый для совместимости
* собственно, сами данные по адресу `0x1359`

Первым слоем всегда (три конфы проверил) лежит следующий набор файлов:
[compat16.zip](https://github.com/e8tools/v8unpack/files/4194351/compat16.zip)

Возможно природа смещения 0x1359 вытекает из размера слоя совместимости. Надо проверить.

**Comment by fishca** [comment]
Исходная конфигурация выгруженная из 1С имеет такой вид
![image](https://user-images.githubusercontent.com/1484649/74641105-ca024980-5181-11ea-8ba8-a07d64bd31a2.png)

Собранная нашим пакером несколько другой
![image](https://user-images.githubusercontent.com/1484649/74641176-eb633580-5181-11ea-83db-7461e6362995.png)

Я так понимаю не записываются даты создания и изменения файлов
из этой структуры: https://github.com/e8tools/v8unpack/blob/5858901f38f21eac5ab5a6ca3c078eb591a04344/src/V8File.h#L294

**Comment by dmpas** [comment]
> Я так понимаю не записываются даты создания и изменения файлов
> из этой структуры:

@fishca есть такое. Я так полагаю, оно никогда никому и не нужно было. Но для порядка можно запилить.
