### ISSUE TITLE
Одним файлом версия есть?

### ISSUE THREAD

**Issue by tormozit** [e8tools/v8unpack#68]
У меня linux нет и знаний про него очень мало. Но есть потребность поддержать работу кода, который сейчас работает через v8unpack, на linux.
Как я понял тут требуется некая "установка".  Какие для нее нужна права?  Еще тут очень много файлов. Есть ли простой вариант с одним файлом  (не нашел)?

**Comment by dmpas** [comment]
как вариант, можно взять пакеты установки и взять из них исполняемый файл.
НО: в линухе критична разрядность, поэтому придётся таскать с собой ДВА исполняемых файла.

**Comment by dmpas** [comment]
@tormozit может для целей ИР лучше напилить компоненту?

**Comment by tormozit** [comment]
Заработало. Правда обнаружил несовместимость по параметрам запуска с оригинальной утилитой под Win. Ну это не 
страшно.
Наверно есть смысл выложить файлы сюда. Может еще кому то пригодятся.

**Comment by dmpas** [comment]
> Правда обнаружил несовместимость по параметрам запуска с оригинальной утилитой под Win

@tormozit  ну-ка, ну-ка? подробнее?

**Comment by tormozit** [comment]
У оригинальной утилиты
-undeflate
У тебя 
-INFLATE

**Comment by dmpas** [comment]
@tormozit 
https://github.com/e8tools/v8unpack/blob/4fcb76b73a5f777827a7bda09873cd6d236e6b81/src/main.cpp#L221

`-undeflate` тоже оставлен для совместимости. Задокументировать забыли :(
