### ISSUE TITLE
При установленном пароле не создается image файл общего модуля

### ISSUE THREAD

**Issue by bolsun** [e8tools/v8unpack#70]
Обычно, при установленном пароле, в папке модуля создается файл **image**, вместе с файлами text и info

![image](https://user-images.githubusercontent.com/2655167/139275647-ab57f57d-7282-4466-a438-5c6d3b57c97e.png)

Но в некоторых случаях вместо этого создается файл в корневой папке распаковки с расширением .0 Файл image отсутствует, а файл text, в котором должен содержаться зашифрованный исходный код - пуст.

![image](https://user-images.githubusercontent.com/2655167/139276937-4765c6d6-5834-46d9-82ef-ec394f8f61a6.png)

![image](https://user-images.githubusercontent.com/2655167/139277800-ec1ee154-b0b1-478f-9576-da2ac0a7bd39.png)

![image](https://user-images.githubusercontent.com/2655167/139276592-8ac085f5-c0f7-4b27-bd97-9efc8efeb0bb.png)

Версия V8Unpack 3.0.42

Пример cf прилагаю.
[test.zip](https://github.com/e8tools/v8unpack/files/7435057/test.zip)

**Comment by dmpas** [comment]
Была ошибка при определениях версий контейнера, которую впилили при начале поддержки формата 8.3.16

Ссылка на пощупать фикс:
https://ci.appveyor.com/api/buildjobs/6flsweff568deywx/artifacts/Release%2Fv8unpack.exe

**Comment by dmpas** [comment]
артефакты на аппвеёре устаревают за месяц.
обновлённая ссылка на пощупать:
https://ci.appveyor.com/api/buildjobs/5pjjkhs4l770q8h8/artifacts/Release%2Fv8unpack.exe


(надеюсь, в январе выпустим 43)

**Comment by bolsun** [comment]
Проблема возникла повторно, но уже в другом виде. на исправленной версии V8Unpack (3.0.43 Версия файла 3.0.43.1)
Версия платформы 8.3.20.1674
Режим совместимости 8.3.12

При распаковке в папке отсутствует файл image.

![image](https://user-images.githubusercontent.com/2655167/160644480-a1a511b0-c2be-4afd-bc6f-438ef725ca52.png)

Файл с зашифрованным исходным текстом модуля, в отличие от предыдущего случая, - не пустой.

![image](https://user-images.githubusercontent.com/2655167/160644671-b564e699-0a3e-4f82-9fac-647b12c9dfae.png)

@dmpas тестовый образец скину в ЛС
