### ISSUE TITLE
В новом формате распаковываются (ключ -P) не все контейнеры

### ISSUE THREAD

**Issue by vkislitsin** [e8tools/v8unpack#72]
В новом формате распаковываются (ключ -P) не все контейнеры
Версия v8unpack - 3.0.42
Конфигурация, на которой выявлена ошибка - Управление торговлей 11.5.7.269 с https://releases.1c.ru/
При распаковке вышеуказанной конфигурации (версия формата cf-файла 8.3.16) с извлечением вложенных контейнеров, 3 контейнера остаются нераспакованными:
6d9fc1d4-bb2f-4c25-a6bd-dfda4072e4d4.0
bc3d31be-e663-4039-b69e-2463e3f201d5.0 
f2b0eab2-e34b-42f8-9b24-5596b4c17d7f.0
![image](https://user-images.githubusercontent.com/25492941/146685657-8c00e9c6-d9d8-43a9-8d9a-b62aacd6ec6f.png)

**Comment by fishca** [comment]
сюда же прибавить http://forum.infostart.ru/forum9/topic274184/message2763719/#message2763719
v8unpack -U для нового формата распаковывает только заглушку (версия 3.0.42)

**Comment by dmpas** [comment]
@vkislitsin Судя по всему, это проблема, описанная в https://github.com/e8tools/v8unpack/issues/70

Вот сборка на попробовать:
https://ci.appveyor.com/api/buildjobs/5pjjkhs4l770q8h8/artifacts/Release%2Fv8unpack.exe

**Comment by vkislitsin** [comment]
@dmpas Да, действительно, в версии 3.0.43 обе проблемы решены.
Но обнаружился небольшой недочет: при распаковке с ключем -U FileHeader содержит 4 лишних байта в конце:
![image](https://user-images.githubusercontent.com/25492941/146761839-332d28a4-9197-41d9-b5b7-8bf5af92ff91.png)

**Comment by dmpas** [comment]
@vkislitsin Возможно. `-U` на 8.3.16 мы особо не прорабатывали. В том числе поэтому 43 версия всё ещё не в людях.
